apiVersion: v1
kind: ConfigMap
metadata:
  name: ogrenci-kayit-config
  namespace: ogrenci-kayit
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/ogrencikayit"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  LOGGING_LEVEL_ROOT: "INFO" 